test_data={'image_png_file': WindowsPath('testdata/files/qa.png')}
http_client={'url': HttpUrl('http://localhost:8000/'), 'timeout': 100.0}
allure_results_dir=allure-results
swagger_coverage_services=[
    {
        "key": "api-course",
        "name": "API Course",
        "tags": ["API", "COURSES"],
        "repository": "https://github.com/dan1795qa/Framework_API-2",
        "swagger_url": "http://localhost:8000/openapi.json",
        "swagger_file": null
    }
]
swagger_coverage_results_dir=./coverage-results
swagger_coverage_history_file=./coverage-history.json
swagger_coverage_history_retention_limit=30
swagger_coverage_html_report_file=./index.html
swagger_coverage_json_report_file=./coverage-report.json
os_info=Windows, 10
python_version=3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]